[package]
name = "starrail-settings"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winreg = "0.55"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1
